export const CAREERS = [
  { id:'sales-assistant', title:'Sales assistant', aliases:['retail assistant','shop assistant','store assistant','retail sales assistant'], sector:'Retail and sales', minSalary:19000, maxSalary:27000, hours:'37 to 42 hours', description:'Serves customers, operates checkouts, replenishes stock and maintains product displays.', skills:['customer service','sales','communication','stock','teamwork'], progression:['retail-manager','sales-representative','retail-buyer'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/sales-assistant' },
  { id:'retail-manager', title:'Retail manager', aliases:['shop manager','store manager','department manager'], sector:'Retail and sales', minSalary:26000, maxSalary:60000, hours:'40 to 42 hours', description:'Runs a store, leads staff, manages targets, stock, customer service and promotions.', skills:['leadership','sales','customer service','stock','management'], progression:['retail-buyer','business-project-manager','business-development-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/retail-manager' },
  { id:'retail-buyer', title:'Retail buyer', aliases:['buyer','wholesale buyer','retail merchandiser'], sector:'Retail and sales', minSalary:26000, maxSalary:50000, hours:'37 to 40 hours', description:'Selects products for retailers and negotiates price, quantity and delivery.', skills:['negotiation','commercial awareness','analysis','retail','planning'], progression:['business-development-manager','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/retail-buyer' },
  { id:'sales-representative', title:'Sales representative', aliases:['sales rep','field sales executive','salesperson'], sector:'Retail and sales', minSalary:23000, maxSalary:50000, hours:'37 to 45 hours', description:'Sells products and services, develops leads and builds customer relationships.', skills:['sales','negotiation','communication','customer service','targets'], progression:['business-development-manager','retail-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/sales-representative' },
  { id:'customer-service-assistant', title:'Customer service assistant', aliases:['customer service adviser','call centre worker','customer support assistant'], sector:'Customer service', minSalary:20000, maxSalary:30000, hours:'37 to 40 hours', description:'Responds to enquiries and handles feedback, complaints and service questions.', skills:['customer service','communication','problem solving','complaints','administration'], progression:['sales-representative','admin-assistant','retail-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/customer-service-assistant' },
  { id:'admin-assistant', title:'Admin assistant', aliases:['office administrator','clerical assistant','administrative assistant'], sector:'Administration', minSalary:21000, maxSalary:28000, hours:'37 to 40 hours', description:'Supports office work, records, documents, meetings, enquiries and schedules.', skills:['administration','organisation','communication','spreadsheets','customer service'], progression:['executive-assistant','payroll-administrator','accounting-technician','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/admin-assistant' },
  { id:'executive-assistant', title:'Executive assistant', aliases:['personal assistant','pa','ea'], sector:'Administration', minSalary:28000, maxSalary:60000, hours:'37 to 42 hours', description:'Supports senior managers with projects, decisions, schedules and client communication.', skills:['organisation','communication','project support','administration','stakeholders'], progression:['business-project-manager','business-development-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/personal-assistant' },
  { id:'payroll-administrator', title:'Payroll administrator', aliases:['payroll clerk','payroll officer'], sector:'Administration and finance', minSalary:22000, maxSalary:35000, hours:'37 to 39 hours', description:'Processes employee pay, deductions, records and payroll deadlines.', skills:['payroll','accuracy','spreadsheets','tax','administration'], progression:['accounting-technician','management-accountant','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/payroll-administrator' },
  { id:'accounting-technician', title:'Accounting technician', aliases:['accounts technician','accounts assistant','finance assistant'], sector:'Finance and accounting', minSalary:24000, maxSalary:35000, hours:'37 to 39 hours', description:'Prepares accounts, tax returns, ledgers and financial records.', skills:['accounting','bookkeeping','spreadsheets','analysis','accuracy'], progression:['management-accountant','private-practice-accountant','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/accounting-technician' },
  { id:'management-accountant', title:'Management accountant', aliases:['chartered management accountant','finance manager'], sector:'Finance and accounting', minSalary:30000, maxSalary:60000, hours:'37 to 39 hours', description:'Oversees company finances, budgets and analysis to improve performance.', skills:['accounting','analysis','budgeting','management','commercial awareness'], progression:['business-project-manager','business-development-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/management-accountant' },
  { id:'private-practice-accountant', title:'Private practice accountant', aliases:['accountant','practice accountant'], sector:'Finance and accounting', minSalary:25000, maxSalary:60000, hours:'37 to 39 hours', description:'Prepares accounts and tax returns for businesses and individuals.', skills:['accounting','tax','analysis','client service','accuracy'], progression:['management-accountant','business-development-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/private-practice-accountant' },
  { id:'business-project-manager', title:'Business project manager', aliases:['project manager','commercial project lead'], sector:'Business and management', minSalary:29000, maxSalary:75000, hours:'Variable by project', description:'Plans work, people and resources to deliver business projects on time and budget.', skills:['project management','leadership','planning','budgeting','stakeholders'], progression:['business-development-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/business-project-manager' },
  { id:'business-development-manager', title:'Business development manager', aliases:['business development','commercial manager','partnerships manager'], sector:'Business and management', minSalary:28000, maxSalary:80000, hours:'Variable by employer', description:'Builds customer relationships and finds opportunities for business growth.', skills:['sales','strategy','negotiation','commercial awareness','relationships'], progression:[], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/business-development-manager' },
  { id:'warehouse-worker', title:'Warehouse worker', aliases:['warehouse operative','warehouse picker'], sector:'Logistics', minSalary:21000, maxSalary:30000, hours:'40 to 48 hours', description:'Receives, stores, picks, packs and dispatches goods.', skills:['warehouse','stock','teamwork','organisation','safety'], progression:['stock-control-assistant','forklift-driver','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/warehouse-worker' },
  { id:'stock-control-assistant', title:'Stock control assistant', aliases:['stock supervisor','stores assistant','supply chain assistant'], sector:'Logistics', minSalary:21000, maxSalary:30000, hours:'37 to 42 hours', description:'Tracks product levels and helps maintain reliable supplies.', skills:['stock','inventory','spreadsheets','organisation','supply chain'], progression:['business-project-manager','retail-buyer'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/stock-control-assistant' },
  { id:'forklift-driver', title:'Forklift driver', aliases:['forklift operator','forklift truck driver'], sector:'Logistics', minSalary:23000, maxSalary:32000, hours:'40 to 48 hours', description:'Moves, loads and unloads goods in warehouses and depots.', skills:['forklift','warehouse','safety','stock','logistics'], progression:['stock-control-assistant','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/forklift-driver' },
  { id:'web-developer', title:'Web developer', aliases:['front end developer','back end developer','full stack developer'], sector:'Technology', minSalary:27000, maxSalary:60000, hours:'37 to 39 hours', description:'Creates and maintains websites and web applications.', skills:['html','css','javascript','coding','problem solving'], progression:['software-developer','app-developer','it-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/web-developer' },
  { id:'software-developer', title:'Software developer', aliases:['programmer','software engineer'], sector:'Technology', minSalary:30000, maxSalary:75000, hours:'Variable by employer', description:'Creates and tests software programs, services and systems.', skills:['software','coding','analysis','problem solving','systems'], progression:['app-developer','it-project-manager','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/software-developer' },
  { id:'app-developer', title:'App developer', aliases:['mobile app developer','application developer'], sector:'Technology', minSalary:31000, maxSalary:65000, hours:'37 to 42 hours', description:'Designs and builds applications for phones, computers and tablets.', skills:['apps','software','coding','mobile','problem solving'], progression:['it-project-manager','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/app-developer' },
  { id:'it-project-manager', title:'IT project manager', aliases:['it project lead','it programme manager','it consultant'], sector:'Technology', minSalary:35000, maxSalary:60000, hours:'Variable by project', description:'Plans and organises teams delivering digital products and services.', skills:['project management','technology','leadership','planning','stakeholders'], progression:['business-project-manager','business-development-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/it-project-manager' },
  { id:'electrician', title:'Electrician', aliases:['electrical fitter','electrical technician','installation electrician'], sector:'Construction and trades', minSalary:26000, maxSalary:45000, hours:'37 to 45 hours', description:'Installs and repairs power, lighting and electrical control systems.', skills:['electrical','installation','safety','problem solving','construction'], progression:['electrical-engineer','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/electrician' },
  { id:'electrical-engineer', title:'Electrical engineer', aliases:['electrical design engineer','electrical systems engineer'], sector:'Engineering', minSalary:27000, maxSalary:58000, hours:'Variable by employer', description:'Designs, builds and maintains electrical machinery and systems.', skills:['electrical','engineering','design','analysis','project management'], progression:['business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/electrical-engineer' },
  { id:'nurse', title:'Nurse', aliases:['adult nurse','registered nurse'], sector:'Healthcare', minSalary:32000, maxSalary:48000, hours:'37 to 42 hours', description:'Assesses and cares for adults in hospitals, clinics and community settings.', skills:['care','healthcare','communication','clinical','teamwork'], progression:['practice-nurse','district-nurse'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/nurse' },
  { id:'practice-nurse', title:'Practice nurse', aliases:['general practice nurse','gp nurse'], sector:'Healthcare', minSalary:40000, maxSalary:57000, hours:'37 to 40 hours', description:'Assesses, screens and treats patients in GP practices.', skills:['nursing','clinical','screening','patient care','healthcare'], progression:[], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/practice-nurse' },
  { id:'district-nurse', title:'District nurse', aliases:['community nurse'], sector:'Healthcare', minSalary:40000, maxSalary:57000, hours:'37 to 40 hours', description:'Provides nursing care in homes, clinics and community settings.', skills:['nursing','community','clinical','patient care','independent working'], progression:[], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/district-nurse' },
  { id:'marketing-executive', title:'Marketing executive', aliases:['digital marketing executive','marketing officer','online marketing officer'], sector:'Marketing', minSalary:23000, maxSalary:50000, hours:'Variable by employer', description:'Promotes products, services and brands through campaigns and communications.', skills:['marketing','digital','campaigns','communication','analysis'], progression:['business-development-manager','business-project-manager'], sourceUrl:'https://nationalcareers.service.gov.uk/job-profiles/marketing-executive' }
];

export const CAREER_DATA_DATE = '30 July 2026';
export const CAREER_SOURCE_NAME = 'National Careers Service';
export const CAREER_SOURCE_NOTE = 'Salary ranges are National Careers Service starter-to-experienced guides. They vary by employer, location, hours and experience.';
